(function(){const A=window.A,{W,H,K}=A,R=A.rect,T=A.text,C=A.circ,L=A.line,rnd=A.rnd,ri=A.ri,cl=A.clamp,S=A.sfx,E=A.emoji;
const ax=k=>(k.r?1:0)-(k.l?1:0),ay=k=>(k.d?1:0)-(k.u?1:0);const shuf=a=>{for(let i=a.length-1;i>0;i--){const j=ri(i+1);[a[i],a[j]]=[a[j],a[i]];}return a;};

/* ---- DECK DUNGEON: card roguelike ---- */
const CARDS={STRIKE:{c:1,d:6,e:'⚔️',tx:'DEAL 6'},DEFEND:{c:1,b:5,e:'🛡️',tx:'BLOCK 5'},BASH:{c:2,d:8,v:2,e:'🔨',tx:'DEAL 8, WEAKEN 2'},FIREBALL:{c:2,d:14,e:'🔥',tx:'DEAL 14'},HEAL:{c:1,h:6,e:'💚',tx:'HEAL 6',x:1},CLEAVE:{c:1,d:4,n:2,e:'🌀',tx:'HIT TWICE FOR 4'},SHIELD:{c:2,b:12,e:'🔰',tx:'BLOCK 12'},FOCUS:{c:0,en:2,e:'⚡',tx:'+2 ENERGY',x:1},POISON:{c:1,p:4,e:'🧪',tx:'POISON 4'},RAGE:{c:1,d:3,s:2,e:'💢',tx:'DEAL 3, +2 STRENGTH'}};
const FOES=[['SLIME','🟢',24,[7,6]],['RAT KING','🐀',34,[9,6]],['SKELETON','💀',44,[11,8]],['GOBLIN','👺',54,[13,10]],['WRAITH','👻',64,[15,9]],['ORC','👹',78,[17,14]],['GOLEM','🗿',95,[19,18]],['DRAGON','🐉',130,[24,20]]];
A.add({id:'deckdungeon',name:'DECK DUNGEON',cat:'CARDS',how:'LEFT/RIGHT PICK A CARD, A PLAYS IT, B ENDS YOUR TURN. BEAT 8 FLOORS.',make(){
 const g={over:null,score:0};let hp=50,maxhp=50,deck=['STRIKE','STRIKE','STRIKE','STRIKE','DEFEND','DEFEND','DEFEND','BASH','FOCUS','CLEAVE'],draw=[],disc=[],hand=[],en,block=0,energy=3,sel=0,floor=0,ph='fight',rew=[],str=0,msg='',mt=0,shakeE=0;
 const newFoe=()=>{const f=FOES[floor];en={n:f[0],e:f[1],hp:f[2],max:f[2],pat:f[3],turn:0,block:0,weak:0,poison:0};str=0;draw=shuf(deck.slice());disc=[];hand=[];startTurn();};
 const intent=()=>en.turn%3===2?{b:en.pat[1]}:{d:en.pat[0]+Math.floor(en.turn/2)*2};
 const drawN=n=>{for(let i=0;i<n;i++){if(!draw.length){draw=shuf(disc);disc=[];}if(draw.length)hand.push(draw.pop());}};
 const startTurn=()=>{block=0;energy=3;disc.push(...hand);hand=[];drawN(5);sel=0;};
 const play=i=>{const c=CARDS[hand[i]];if(c.c>energy){msg='NOT ENOUGH ENERGY';mt=40;S('lose');return;}energy-=c.c;if(c.d){for(let k=0;k<(c.n||1);k++){let d=c.d+str;if(en.weak>0)d=Math.ceil(d*1.5);const ab=Math.min(en.block,d);en.block-=ab;en.hp-=d-ab;}shakeE=8;S('hit');A.burst(230,100,K.r,12,2.5);}if(c.b)block+=c.b;if(c.v)en.weak+=c.v;if(c.h)hp=Math.min(maxhp,hp+c.h);if(c.en)energy+=c.en;if(c.p)en.poison+=c.p;if(c.s)str+=c.s;if(c.b)S('blip');disc.push(hand.splice(i,1)[0]);sel=Math.min(sel,Math.max(0,hand.length-1));
  if(en.hp<=0){floor++;g.score+=100*floor+hp;S('win');A.confetti();if(floor>=FOES.length){g.over='DUNGEON CLEARED! WIN';return;}ph='reward';const keys=Object.keys(CARDS);rew=shuf(keys.slice()).slice(0,3);sel=0;}};
 const enemyTurn=()=>{if(en.poison>0){en.hp-=en.poison;en.poison--;if(en.hp<=0){play.call;floor++;g.score+=100*floor+hp;if(floor>=FOES.length){g.over='DUNGEON CLEARED! WIN';return;}ph='reward';rew=shuf(Object.keys(CARDS)).slice(0,3);sel=0;return;}}en.block=0;const it=intent();if(it.d){const ab=Math.min(block,it.d);hp-=it.d-ab;S(it.d-ab>0?'boom':'hit');A.shake=it.d-ab>0?6:0;}if(it.b)en.block+=it.b;if(en.weak>0)en.weak--;en.turn++;if(hp<=0){g.over='SLAIN ON FLOOR '+(floor+1);return;}startTurn();};
 newFoe();
 g.update=()=>{if(mt)mt--;if(shakeE)shakeE--;const h=A.hit(0);if(ph==='reward'){if(h.l)sel=(sel+2)%3;if(h.r)sel=(sel+1)%3;if(h.a){deck.push(rew[sel]);maxhp+=4;hp=Math.min(maxhp,hp+12);ph='fight';newFoe();S('coin');}if(h.b){hp=Math.min(maxhp,hp+18);ph='fight';newFoe();}return;}
  if(h.l&&hand.length)sel=(sel+hand.length-1)%hand.length;if(h.r&&hand.length)sel=(sel+1)%hand.length;if(h.l||h.r)S('blip');if(h.a&&hand.length)play(sel);if(h.b)enemyTurn();};
 g.draw=()=>{A.cls('#1a1024');R(0,150,W,90,'#241a34');for(let i=0;i<8;i++)R(i*42,150,40,4,'#3a2a48');if(ph==='reward'){T('CHOOSE A CARD (B = REST +18 HP)',160,30,K.y,1,'c');rew.forEach((k,i)=>card(70+i*90,80,k,i===sel,true));return;}
  const sx=shakeE?(Math.random()-.5)*6:0;E(en.e,230+sx,100,56);T(en.n,230,40,K.w,1,'c');R(190,138,80,6,K.d);R(190,138,80*Math.max(0,en.hp)/en.max,6,K.r);T(Math.max(0,en.hp)+'/'+en.max,230,146,K.w,1,'c');if(en.block)T('🛡 '+en.block,190,128,K.c,1);if(en.weak)T('WEAK '+en.weak,230,154,K.y,1,'c');if(en.poison)T('POISON '+en.poison,230,162,K.g,1,'c');
  const it=intent();T(it.d?'INTENT: ATTACK '+it.d:'INTENT: BLOCK '+it.b,230,26,it.d?K.r:K.c,1,'c');A.person(70,140,{c:'#3a5ab0',pants:'#2a2a3a',st:0,s:1.6,id:2,arm2:-1});T('HP '+hp+'/'+maxhp,70,146,K.g,1,'c');if(block)T('BLOCK '+block,70,156,K.c,1,'c');if(str)T('STR +'+str,70,166,K.o,1,'c');
  for(let i=0;i<3;i++)C(14+i*12,20,5,i<energy?K.y:'#3a3a4a');if(energy>3)T('+'+(energy-3),52,17,K.y,1);T('FLOOR '+(floor+1)+'/8',W-6,6,K.w,1,'r');T('DECK '+draw.length+' DISCARD '+disc.length,6,30,K.gr,1);
  const n=hand.length,w=Math.min(56,280/n);hand.forEach((k,i)=>card(160-n*w/2+i*w+w/2-24,176-(i===sel?10:0),k,i===sel));if(mt)T(msg,160,60,K.r,1,'c');T('B END TURN',W-6,230,K.gr,1,'r');};
 const card=(x,y,k,on,big)=>{const c=CARDS[k],s=big?1.5:1;R(x,y,48*s,60*s,on?'#fff3d6':'#d8ccb0');A.box(x,y,48*s,60*s,on?K.y:'#6a5a3a');C(x+7*s,y+7*s,5*s,K.y);T(c.c,x+7*s,y+5*s,K.k,1,'c');E(c.e,x+24*s,y+26*s,18*s);T(k,x+24*s,y+42*s,K.k,1,'c');if(big||on)T(c.tx,x+24*s,y+(big?100:70),on?K.w:K.gr,1,'c');};
 return g;}});

/* ---- CASTLE DEFENSE: tower defence ---- */
A.add({id:'castletd',name:'CASTLE DEFENSE',cat:'ACTION',how:'MOVE THE CURSOR. A BUILDS, B CHANGES TOWER. STOP 15 WAVES REACHING THE CASTLE.',make(){
 const g={over:null,score:0},GW=16,GH=11,CS=20,OY=20;const PATH=[[0,2],[5,2],[5,7],[10,7],[10,3],[14,3],[14,9],[15,9]];const path=[];for(let i=0;i<PATH.length-1;i++){const[a,b]=[PATH[i],PATH[i+1]];const dx=Math.sign(b[0]-a[0]),dy=Math.sign(b[1]-a[1]);let x=a[0],y=a[1];while(x!==b[0]||y!==b[1]){path.push([x,y]);x+=dx;y+=dy;}}path.push(PATH[PATH.length-1]);
 const onPath=new Set(path.map(p=>p.join(',')));const TT=[{n:'ARROW',c:25,r:52,rate:22,d:4,col:K.y,e:'🏹'},{n:'CANNON',c:60,r:44,rate:60,d:12,sp:24,col:K.o,e:'💣'},{n:'FROST',c:45,r:46,rate:40,d:1,slow:90,col:K.c,e:'❄️'}];
 let towers=[],mobs=[],shots=[],gold=80,lives=20,wave=0,toSpawn=0,spT=0,cur={x:3,y:5},type=0,brk=180;
 const wp=i=>[path[i][0]*CS+CS/2,OY+path[i][1]*CS+CS/2];
 g.update=()=>{const h=A.hit(0);if(h.l)cur.x=Math.max(0,cur.x-1);if(h.r)cur.x=Math.min(GW-1,cur.x+1);if(h.u)cur.y=Math.max(0,cur.y-1);if(h.d)cur.y=Math.min(GH-1,cur.y+1);if(A.mouse.t>0){cur.x=cl(Math.floor(A.mouse.x/CS),0,GW-1);cur.y=cl(Math.floor((A.mouse.y-OY)/CS),0,GH-1);}if(h.b){type=(type+1)%3;S('blip');}
  if(h.a){const k=cur.x+','+cur.y,ex=towers.find(t=>t.x===cur.x&&t.y===cur.y);if(ex){if(gold>=TT[ex.k].c&&ex.lv<3){gold-=TT[ex.k].c;ex.lv++;S('coin');}}else if(!onPath.has(k)&&gold>=TT[type].c){gold-=TT[type].c;towers.push({x:cur.x,y:cur.y,k:type,cd:0,lv:1});S('hit');}else S('lose');}
  if(toSpawn===0&&!mobs.length){if(brk>0)brk--;else{wave++;if(wave>15){g.over='CASTLE SAVED! WIN';A.confetti();return;}toSpawn=6+wave*2;spT=0;brk=240;}}
  if(toSpawn>0&&--spT<=0){spT=Math.max(14,40-wave*2);toSpawn--;const boss=wave%5===0&&toSpawn===0;mobs.push({i:0,f:0,hp:(8+wave*6)*(boss?8:1),max:(8+wave*6)*(boss?8:1),sp:boss?.35:.5+wave*.02,slow:0,boss});}
  for(const m of mobs){const s=m.sp*(m.slow>0?.45:1);if(m.slow>0)m.slow--;m.f+=s/CS;while(m.f>=1&&m.i<path.length-1){m.f-=1;m.i++;}if(m.i>=path.length-1){m.gone=1;lives-=m.boss?5:1;S('lose');if(lives<=0){g.over='CASTLE FELL ON WAVE '+wave;return;}}const a=wp(m.i),b=wp(Math.min(path.length-1,m.i+1));m.x=a[0]+(b[0]-a[0])*m.f;m.y=a[1]+(b[1]-a[1])*m.f;}
  for(const t of towers){if(t.cd>0){t.cd--;continue;}const T_=TT[t.k],tx=t.x*CS+CS/2,ty=OY+t.y*CS+CS/2,rng=T_.r+t.lv*6;const tgt=mobs.filter(m=>!m.gone&&m.hp>0&&Math.hypot(m.x-tx,m.y-ty)<rng).sort((a,b)=>(b.i+b.f)-(a.i+a.f))[0];if(tgt){t.cd=T_.rate;shots.push({x:tx,y:ty,m:tgt,k:t.k,d:T_.d*t.lv});S(t.k===1?'boom':'shoot');}}
  for(const s of shots){const dx=s.m.x-s.x,dy=s.m.y-s.y,d=Math.hypot(dx,dy);if(d<5||s.m.gone){if(!s.m.gone){const hitList=s.k===1?mobs.filter(m=>Math.hypot(m.x-s.m.x,m.y-s.m.y)<TT[1].sp):[s.m];hitList.forEach(m=>{m.hp-=s.d;if(s.k===2)m.slow=TT[2].slow;});if(s.k===1)A.burst(s.m.x,s.m.y,K.o,10,2);}s.done=1;continue;}s.x+=dx/d*5;s.y+=dy/d*5;}shots=shots.filter(s=>!s.done);
  mobs.forEach(m=>{if(m.hp<=0&&!m.gone){m.gone=1;gold+=m.boss?40:4+(wave/3|0);g.score+=m.boss?100:10;A.burst(m.x,m.y,K.r,6,1.5);}});mobs=mobs.filter(m=>!m.gone);};
 g.draw=()=>{A.cls('#4a8a3a');for(let y=0;y<GH;y++)for(let x=0;x<GW;x++){if(onPath.has(x+','+y))R(x*CS,OY+y*CS,CS,CS,'#c4a56a');else if((x+y)%2)R(x*CS,OY+y*CS,CS,CS,'#4f9040');}E('🏰',15*CS+CS/2,OY+9*CS+6,26);E('🕳️',CS/2,OY+2*CS+CS/2,16);
  towers.forEach(t=>{const x=t.x*CS,y=OY+t.y*CS;R(x+2,y+2,CS-4,CS-4,'#6a6a78');E(TT[t.k].e,x+CS/2,y+CS/2,14);for(let i=0;i<t.lv;i++)R(x+3+i*5,y+CS-5,4,3,K.y);});
  mobs.forEach(m=>{E(m.boss?'👹':'🧟',m.x,m.y,m.boss?22:15);R(m.x-8,m.y-12,16,2,K.d);R(m.x-8,m.y-12,16*m.hp/m.max,2,m.slow>0?K.c:K.r);});shots.forEach(s=>C(s.x,s.y,s.k===1?3:2,TT[s.k].col));
  const ct=towers.find(t=>t.x===cur.x&&t.y===cur.y);A.box(cur.x*CS,OY+cur.y*CS,CS,CS,K.w);if(ct)A.ring(cur.x*CS+CS/2,OY+cur.y*CS+CS/2,TT[ct.k].r+ct.lv*6,'rgba(255,255,255,.4)');
  R(0,0,W,20,'#1a1238');T('💰',0,0,K.y,1);T('GOLD '+gold,6,6,K.y,1);T('LIVES '+lives,80,6,K.r,1);T('WAVE '+Math.max(1,wave)+'/15',150,6,K.w,1);T((ct?'UPGRADE ':'')+TT[ct?ct.k:type].n+' '+TT[ct?ct.k:type].c,W-6,6,K.c,1,'r');};
 return g;}});

/* ---- JELLY MATCH: match-3 with power-ups ---- */
const JC=['🍬','🍭','🍫','🍩','🍪','🧁'];
A.add({id:'jellymatch',name:'JELLY MATCH',cat:'PUZZLE',how:'A PICKS A SWEET, AN ARROW SWAPS IT. MATCH 3+. 4 = STRIPED, 5 = COLOUR BOMB. 25 MOVES.',make(){
 const g={over:null,score:0},N=8,CS=26,OX=56,OY=16;let b=[],c={x:3,y:3},held=false,moves=25,target=3000,busy=0,level=1;
 const cell=()=>({k:ri(6),sp:0,dy:0});for(let i=0;i<N*N;i++)b.push(cell());const at=(x,y)=>x>=0&&y>=0&&x<N&&y<N?b[y*N+x]:null;
 const findRuns=()=>{const hit=new Set(),specials=[];for(let y=0;y<N;y++)for(let x=0;x<N;){let l=1;while(x+l<N&&at(x+l,y).k===at(x,y).k&&at(x,y).k>=0)l++;if(l>=3){for(let i=0;i<l;i++)hit.add(y*N+x+i);if(l>=4)specials.push({i:y*N+x+1,sp:l>=5?3:1,k:at(x,y).k});}x+=l;}
  for(let x=0;x<N;x++)for(let y=0;y<N;){let l=1;while(y+l<N&&at(x,y+l).k===at(x,y).k&&at(x,y).k>=0)l++;if(l>=3){for(let i=0;i<l;i++)hit.add((y+i)*N+x);if(l>=4)specials.push({i:(y+1)*N+x,sp:l>=5?3:2,k:at(x,y).k});}y+=l;}return{hit,specials};};
 while(findRuns().hit.size){findRuns().hit.forEach(i=>b[i]=cell());}
 const blast=(set)=>{let more=true;while(more){more=false;[...set].forEach(i=>{const s=b[i];if(s.sp===1){s.sp=0;for(let x=0;x<N;x++)if(!set.has((i/N|0)*N+x)){set.add((i/N|0)*N+x);more=true;}}if(s.sp===2){s.sp=0;for(let y=0;y<N;y++)if(!set.has(y*N+i%N)){set.add(y*N+i%N);more=true;}}});}};
 const resolve=(chain)=>{const{hit,specials}=findRuns();if(!hit.size)return false;blast(hit);g.score+=hit.size*20*chain;S(chain>1?'score':'coin');hit.forEach(i=>A.burst(OX+(i%N)*CS+CS/2,OY+((i/N)|0)*CS+CS/2,K.p,3,1.5));const keep=specials.filter(s=>hit.has(s.i));hit.forEach(i=>b[i].k=-1);keep.forEach(s=>{b[s.i]={k:s.sp===3?6:s.k,sp:s.sp,dy:0};});
  for(let x=0;x<N;x++){const col=[];for(let y=N-1;y>=0;y--)if(b[y*N+x].k!==-1)col.push(b[y*N+x]);let y=N-1;for(const q of col){q.dy+=(y-(b.indexOf(q)/N|0))*0;b[y*N+x]=q;y--;}const gap=y+1;for(;y>=0;y--){const n=cell();n.dy=-(gap)*CS;b[y*N+x]=n;}for(let yy=0;yy<N;yy++){const q=b[yy*N+x];q.dy=Math.min(q.dy,0)||-(gap?CS*0:0);}}return true;};
 g.update=()=>{b.forEach(q=>{if(q.dy<0)q.dy=Math.min(0,q.dy+6);});if(busy>0){busy--;if(busy===0){let ch=2;if(resolve(ch)){busy=14;}else if(g.score>=target){S('win');A.confetti();level++;target+=3000+level*1000;moves+=20;}else if(moves<=0)g.over=g.score>=target?'SWEET! WIN':'OUT OF MOVES';}return;}
  const h=A.hit(0);if(!held){if(h.l)c.x=Math.max(0,c.x-1);if(h.r)c.x=Math.min(N-1,c.x+1);if(h.u)c.y=Math.max(0,c.y-1);if(h.d)c.y=Math.min(N-1,c.y+1);if(h.a){held=true;S('blip');}return;}
  const d=h.l?[-1,0]:h.r?[1,0]:h.u?[0,-1]:h.d?[0,1]:null;if(h.a||h.b){held=false;return;}if(!d)return;const nx=c.x+d[0],ny=c.y+d[1];if(!at(nx,ny)){held=false;return;}const i=c.y*N+c.x,j=ny*N+nx;held=false;
  if(b[i].sp===3||b[j].sp===3){const bomb=b[i].sp===3?i:j,other=bomb===i?j:i,kk=b[other].k;const set=new Set([bomb]);b.forEach((q,k)=>{if(q.k===kk)set.add(k);});blast(set);g.score+=set.size*40;set.forEach(k=>b[k].k=-1);S('boom');A.shake=6;moves--;
   for(let x=0;x<N;x++){const col=[];for(let y=N-1;y>=0;y--)if(b[y*N+x].k!==-1)col.push(b[y*N+x]);let y=N-1;for(const q of col){b[y*N+x]=q;y--;}for(;y>=0;y--){const n=cell();n.dy=-CS*2;b[y*N+x]=n;}}busy=14;return;}
  [b[i],b[j]]=[b[j],b[i]];if(findRuns().hit.size){moves--;c.x=nx;c.y=ny;resolve(1);busy=14;}else{[b[i],b[j]]=[b[j],b[i]];S('lose');}};
 g.draw=()=>{A.cls('#ffd6e8');R(OX-4,OY-4,N*CS+8,N*CS+8,'#ffffff');for(let y=0;y<N;y++)for(let x=0;x<N;x++){const q=b[y*N+x];R(OX+x*CS,OY+y*CS,CS-1,CS-1,(x+y)%2?'#ffe9f3':'#fff4fa');if(q.k<0)continue;const px=OX+x*CS+CS/2,py=OY+y*CS+CS/2+q.dy;if(q.sp===3){C(px,py,10,'#3a2a48');for(let k=0;k<6;k++)C(px+Math.cos(k+A.t*.1)*6,py+Math.sin(k+A.t*.1)*6,2,[K.r,K.y,K.g,K.c,K.p,K.o][k]);continue;}E(JC[q.k],px,py,20);if(q.sp===1)R(px-10,py-1,20,3,'rgba(255,255,255,.9)');if(q.sp===2)R(px-1,py-10,3,20,'rgba(255,255,255,.9)');}
  A.box(OX+c.x*CS,OY+c.y*CS,CS,CS,held?K.r:'#8a3a6a');if(held)A.box(OX+c.x*CS+1,OY+c.y*CS+1,CS-2,CS-2,K.r);T('SCORE',290,30,'#8a3a6a',1,'c');T(g.score,290,42,K.k,1,'c');T('TARGET',290,70,'#8a3a6a',1,'c');T(target,290,82,K.k,1,'c');T('MOVES',290,110,'#8a3a6a',1,'c');T(moves,290,122,moves<5?K.r:K.k,2,'c');T('LEVEL '+level,290,160,'#8a3a6a',1,'c');};
 return g;}});

/* ---- WORM ARENA: slither-style ---- */
A.add({id:'wormarena',name:'WORM ARENA',cat:'ACTION',mouse:1,how:'STEER WITH LEFT/RIGHT OR THE MOUSE. HOLD A TO BOOST. EAT ORBS, CUT OFF OTHER WORMS.',make(){
 const g={over:null,score:0},AR=420;let worms=[],food=[],t=0;const mkW=(x,y,col,ai)=>({pts:Array.from({length:14},()=>({x,y})),a:rnd(6.28),len:14,col,ai,dead:false,boost:false});
 worms.push(mkW(0,0,K.c,false));for(let i=0;i<6;i++)worms.push(mkW(rnd(600)-300,rnd(600)-300,[K.p,K.o,K.g,K.y,'#b070ff',K.r][i],true));for(let i=0;i<160;i++)food.push({x:rnd(800)-400,y:rnd(800)-400,v:1,c:[K.r,K.y,K.c,K.p,K.g][ri(5)]});
 const me=()=>worms[0];
 g.update=()=>{t++;for(const w of worms){if(w.dead)continue;const hd=w.pts[0];if(w.ai){let tgt=null,bd=1e9;for(const f of food){const d=(f.x-hd.x)**2+(f.y-hd.y)**2;if(d<bd){bd=d;tgt=f;}}let want=tgt?Math.atan2(tgt.y-hd.y,tgt.x-hd.x):w.a;for(const o of worms){if(o===w||o.dead)continue;for(const p of o.pts){if((p.x-hd.x)**2+(p.y-hd.y)**2<900){want=Math.atan2(hd.y-p.y,hd.x-p.x);break;}}}if(Math.hypot(hd.x,hd.y)>AR-40)want=Math.atan2(-hd.y,-hd.x);let da=want-w.a;while(da>3.14)da-=6.28;while(da<-3.14)da+=6.28;w.a+=cl(da,-.08,.08);w.boost=false;}
   else{const k=A.in(0);if(A.mouse.t>0){const want=Math.atan2(A.mouse.y-120,A.mouse.x-160);let da=want-w.a;while(da>3.14)da-=6.28;while(da<-3.14)da+=6.28;w.a+=cl(da,-.09,.09);}else w.a+=ax(k)*.08;w.boost=(k.a||A.mouse.down)&&w.len>12;}
   const sp=w.boost?3.2:1.9;const nh={x:hd.x+Math.cos(w.a)*sp,y:hd.y+Math.sin(w.a)*sp};w.pts.unshift(nh);while(w.pts.length>w.len)w.pts.pop();if(w.boost&&t%8===0){w.len--;const tl=w.pts[w.pts.length-1];food.push({x:tl.x,y:tl.y,v:1,c:w.col});}
   food=food.filter(f=>{if((f.x-nh.x)**2+(f.y-nh.y)**2<64){w.len+=f.v;if(!w.ai){g.score+=f.v;}return false;}return true;});if(Math.hypot(nh.x,nh.y)>AR)kill(w);
   for(const o of worms){if(o===w||o.dead)continue;for(let i=2;i<o.pts.length;i+=2){const p=o.pts[i];if((p.x-nh.x)**2+(p.y-nh.y)**2<40){kill(w);break;}}if(w.dead)break;}}
  while(food.length<160)food.push({x:rnd(800)-400,y:rnd(800)-400,v:1,c:[K.r,K.y,K.c,K.p,K.g][ri(5)]});worms.forEach((w,i)=>{if(w.dead&&w.ai&&(w.respawn=(w.respawn||0)+1)>180)worms[i]=mkW(rnd(600)-300,rnd(600)-300,w.col,true);});};
 const kill=w=>{w.dead=true;w.pts.forEach((p,i)=>{if(i%2===0)food.push({x:p.x+rnd(6)-3,y:p.y+rnd(6)-3,v:2,c:w.col});});if(w===worms[0]){g.over='LENGTH '+w.len;S('boom');}else S('hit');};
 g.draw=()=>{A.cls('#0a0a14');const hd=me().pts[0],cx=hd.x-160,cy=hd.y-120;for(let x=-400;x<=400;x+=40)R(x-cx,-400-cy,1,800,'#151525');for(let y=-400;y<=400;y+=40)R(-400-cx,y-cy,800,1,'#151525');A.c.strokeStyle=K.r;A.c.lineWidth=3;A.c.beginPath();A.c.arc(-cx,-cy,AR,0,7);A.c.stroke();
  food.forEach(f=>{const x=f.x-cx,y=f.y-cy;if(x>-5&&x<W+5&&y>-5&&y<H+5)C(x,y,2+f.v,f.c);});worms.forEach(w=>{if(w.dead)return;for(let i=w.pts.length-1;i>=0;i-=2){const p=w.pts[i],r=4+Math.min(6,w.len/30);C(p.x-cx,p.y-cy,r,i%4===0?w.col:A.mix(w.col,'#000000',.2));}const h=w.pts[0];C(h.x-cx+Math.cos(w.a+.5)*3,h.y-cy+Math.sin(w.a+.5)*3,2,'#fff');C(h.x-cx+Math.cos(w.a-.5)*3,h.y-cy+Math.sin(w.a-.5)*3,2,'#fff');});
  T('LENGTH '+me().len,6,6,K.y,2);const top=worms.filter(w=>!w.dead).sort((a,b)=>b.len-a.len).slice(0,3);top.forEach((w,i)=>T((i+1)+'. '+(w.ai?'CPU':'YOU')+' '+w.len,W-6,6+i*10,w.col,1,'r'));};
 return g;}});

/* ---- WORD GUESS ---- */
const WORDS='APPLE BEACH BRAIN BREAD BRUSH CHAIR CHEST CHORD CLICK CLOCK CLOUD DANCE DIARY DRINK EARTH FEAST FIELD FLAME FRUIT GHOST GLASS GRAPE GREEN HEART HOUSE JUICE LASER LEMON LIGHT MAGIC MONEY MUSIC NIGHT OCEAN PAINT PARTY PHONE PIANO PIXEL PLANE PLANT PLATE QUEEN RADIO RIVER ROBOT SCALE SHEEP SHIRT SMILE SNAKE SPACE SPOON STAGE STONE STORM SUGAR TABLE TIGER TOAST TOWER TRAIN TRUCK WATER WHALE WORLD ZEBRA BLAZE CRANE DRIFT EAGLE FROST GLOBE HONEY IVORY JOKER KNIFE LUNAR MANGO NOBLE OLIVE PEARL QUEST RANCH SOLAR THUMB ULTRA VIVID WALTZ YACHT ARENA BONUS CANDY DELTA EMBER FLUTE GIANT HABIT INDEX JELLY KOALA LLAMA METRO NINJA ORBIT PANDA QUILT RHINO SALSA TANGO UNITY VAPOR WHEAT'.split(' ');
A.add({id:'wordguess',name:'WORD GUESS',cat:'PUZZLE',typing:1,how:'TYPE A 5-LETTER WORD, ENTER TO GUESS. GREEN = RIGHT SPOT, YELLOW = IN THE WORD. 6 TRIES.',make(){
 const g={over:null,score:0},KB=['QWERTYUIOP','ASDFGHJKL>','ZXCVBNM<'];let ans=WORDS[ri(WORDS.length)],rows=[],curW='',kc={x:0,y:0},used={},round=1,msg='',mt=0,streak=0;
 const mark=w=>{const res=Array(5).fill(0),a=ans.split('');for(let i=0;i<5;i++)if(w[i]===a[i]){res[i]=2;a[i]='';}for(let i=0;i<5;i++)if(!res[i]){const j=a.indexOf(w[i]);if(j>=0){res[i]=1;a[j]='';}}return res;};
 const key=ch=>{if(ch==='<'){curW=curW.slice(0,-1);S('blip');return;}if(ch==='>'){if(curW.length<5){msg='NEED 5 LETTERS';mt=40;S('lose');return;}const r=mark(curW);rows.push({w:curW,r});curW.split('').forEach((c,i)=>used[c]=Math.max(used[c]||0,r[i]+1));S(r.every(v=>v===2)?'win':'hit');
  if(r.every(v=>v===2)){streak++;g.score+=(7-rows.length)*100;msg='SOLVED IN '+rows.length;mt=90;A.confetti();}else if(rows.length>=6){msg='IT WAS '+ans;mt=120;g.fail=1;}curW='';return;}if(curW.length<5){curW+=ch;S('blip');}};
 g.update=()=>{if(mt>0){if(--mt===0&&(g.fail||rows.length&&rows[rows.length-1].r.every(v=>v===2))){if(g.fail){g.over='STREAK '+streak;return;}round++;ans=WORDS[ri(WORDS.length)];rows=[];used={};}return;}
  while(A.typed.length)key(A.typed.shift());const h=A.hit(0);if(h.l)kc.x=(kc.x+KB[kc.y].length-1)%KB[kc.y].length;if(h.r)kc.x=(kc.x+1)%KB[kc.y].length;if(h.u){kc.y=(kc.y+2)%3;kc.x=Math.min(kc.x,KB[kc.y].length-1);}if(h.d){kc.y=(kc.y+1)%3;kc.x=Math.min(kc.x,KB[kc.y].length-1);}if(h.a)key(KB[kc.y][kc.x]);if(h.b)key('<');};
 g.draw=()=>{A.cls('#121213');const col=v=>v===2?'#538d4e':v===1?'#b59f3b':'#3a3a3c';for(let r=0;r<6;r++)for(let i=0;i<5;i++){const x=110+i*21,y=8+r*23;const row=rows[r];const ch=row?row.w[i]:r===rows.length?curW[i]:'';R(x,y,19,21,row?col(row.r[i]):'#121213');A.box(x,y,19,21,row?col(row.r[i]):ch?'#565758':'#3a3a3c');if(ch)T(ch,x+10,y+7,K.w,1,'c');}
  KB.forEach((row,y)=>[...row].forEach((ch,x)=>{const px=20+x*28+(y===1?6:y===2?20:0),py=154+y*26,u=used[ch];R(px,py,24,22,u?col(u-1):'#818384');if(kc.x===x&&kc.y===y)A.box(px-1,py-1,26,24,K.y);T(ch==='>'?'OK':ch==='<'?'DEL':ch,px+12,py+8,K.w,1,'c');}));T('WORD '+round,6,6,K.gr,1);T('STREAK '+streak,W-6,6,K.y,1,'r');if(mt)T(msg,160,140,K.y,1,'c');};
 return g;}});
})();
