// CRITTER KART — tiny WebAudio synth: engines per player, pickups, boosts, hits, countdown, fanfare.
export class Sound{
 constructor(){this.ctx=null;this.eng=[];this.on=true;}
 init(){if(this.ctx)return;try{this.ctx=new (window.AudioContext||window.webkitAudioContext)();this.master=this.ctx.createGain();this.master.gain.value=.35;this.master.connect(this.ctx.destination);}catch(e){this.ctx=null;}}
 engines(n){if(!this.ctx)return;while(this.eng.length<n){const o=this.ctx.createOscillator(),o2=this.ctx.createOscillator(),g=this.ctx.createGain(),f=this.ctx.createBiquadFilter();o.type='sawtooth';o2.type='square';f.type='lowpass';f.frequency.value=900;g.gain.value=0;o.connect(f);o2.connect(f);f.connect(g);g.connect(this.master);o.start();o2.start();this.eng.push({o,o2,g,f});}
  this.eng.forEach((e,i)=>{if(i>=n)e.g.gain.value=0;});}
 engine(i,speed,type,on){const e=this.eng[i];if(!e||!this.ctx)return;const t=this.ctx.currentTime,base=type==='plane'?70:type==='hover'?95:55;e.o.frequency.setTargetAtTime(base+speed*4.2,t,.06);e.o2.frequency.setTargetAtTime((base+speed*4.2)*.501,t,.06);e.g.gain.setTargetAtTime(on?.05+Math.min(.07,speed*.002):0,t,.1);}
 stop(){this.eng.forEach(e=>e.g.gain.value=0);}
 blip(f,d=.1,type='square',v=.15,slide=0){if(!this.ctx||!this.on)return;const t=this.ctx.currentTime,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.setValueAtTime(f,t);if(slide)o.frequency.exponentialRampToValueAtTime(Math.max(30,f+slide),t+d);g.gain.setValueAtTime(v,t);g.gain.exponentialRampToValueAtTime(.001,t+d);o.connect(g);g.connect(this.master);o.start(t);o.stop(t+d+.02);}
 noise(d=.3,v=.2,f=800){if(!this.ctx||!this.on)return;const t=this.ctx.currentTime,b=this.ctx.createBuffer(1,this.ctx.sampleRate*d,this.ctx.sampleRate),a=b.getChannelData(0);for(let i=0;i<a.length;i++)a[i]=(Math.random()*2-1)*(1-i/a.length);const s=this.ctx.createBufferSource(),fl=this.ctx.createBiquadFilter(),g=this.ctx.createGain();s.buffer=b;fl.type='lowpass';fl.frequency.value=f;g.gain.value=v;s.connect(fl);fl.connect(g);g.connect(this.master);s.start(t);}
 play(k){switch(k){case'beep':this.blip(440,.18,'square',.12);break;case'go':this.blip(880,.4,'square',.14);break;case'pod':this.blip(660,.08,'triangle',.12,500);setTimeout(()=>this.blip(990,.1,'triangle',.1),70);break;
  case'berry':this.blip(1200,.06,'sine',.12,400);break;case'coin':this.blip(1500,.08,'triangle',.12);setTimeout(()=>this.blip(2000,.12,'triangle',.1),60);break;case'zip':this.blip(200,.4,'sawtooth',.1,900);break;
  case'fire':this.noise(.25,.18,1800);this.blip(300,.2,'sawtooth',.06,-200);break;case'hit':this.noise(.4,.3,600);this.blip(180,.35,'square',.1,-120);break;case'pop':this.blip(900,.12,'sine',.15,-600);break;
  case'lap':[523,659,784].forEach((f,i)=>setTimeout(()=>this.blip(f,.12,'triangle',.12),i*90));break;case'win':[523,659,784,1047,784,1047].forEach((f,i)=>setTimeout(()=>this.blip(f,.18,'triangle',.14),i*120));break;
  case'lose':[392,330,262].forEach((f,i)=>setTimeout(()=>this.blip(f,.25,'triangle',.12),i*180));break;case'ring':this.blip(1046,.1,'sine',.12,600);break;case'splash':this.noise(.5,.25,1200);break;case'door':this.blip(330,.3,'triangle',.1,330);break;
  case'bolt':this.noise(.6,.35,3000);break;case'drop':this.blip(240,.15,'square',.1,-120);break;case'balloon':[784,988,1175,1568].forEach((f,i)=>setTimeout(()=>this.blip(f,.15,'triangle',.13),i*100));break;}}}
